### PR TITLE
corrected issue with latest_update in input view

### LINKED ISSUE #1407: Uncaught Range Error
related to https://community.openenergymonitor.org/t/uncaught-range-error-10-1-6/11919

js error while finding node latest input time
delwedd

### PR DESCRIPTION
**Pull request by emrysr**
fix #1407

### CODE REVIEW

**Comment by TrystanLea** [comment]
Does this apply to the new vue.js based input view @emrysr ?

**Comment by emrysr** [comment]
@TrystanLea  - I've corrected the conflict. 
Yes this conflict was due to the changes that introduced vue.js into the input view after this pull request.

**Comment by TrystanLea** [comment]
thanks @emrysr is there any difference now in this change? seems to just be adding a couple of new lines?

**Comment by emrysr** [comment]
actually no! you're right... issue #1407 will have been fixed by integrating the vue.js version in pull request #1360 

i'll close this pull request

**Pull request closed without merging**
