### PR TITLE
Add formatting to improve clipboard render

### PR DESCRIPTION
**Pull request by Paul-Reed**
Memory	RAM	Used 53.44%Total: 875.78 MB Used: 468.02 MB Free: 407.76 MB
               Swap	Used 76.32%Total: 100 MB Used: 76.31 MB Free: 23.68 MB
Adds colon to 'Used' & space after '%'
Remove whitespace
@thib66 The clipboard copies 'Shutdown/Reboot' alongside the CPU Temp, could we use Regex to ensure it's not displayed?

shot

### CODE REVIEW

**Comment by thib66** [comment]
Hello Paul,
yes regex can be used, we probably need to add 
image
at the end of the line 385. Could you add this for me and test the change?
Thanks a lot,
Aymeric

**Comment by thib66** [comment]
Paul, sorry the code sent only delete only the button tag and not the content.
My apologizes.

**Comment by thib66** [comment]
Paul, please try this : 
image

**Comment by Paul-Reed** [comment]
Thanks, yes, I've added that to the PR.
I'm out for the afternoon, but will look at the other forum feedback this evening, and update the branch.

Paul

**Pull request merged**
