### PR TITLE
Feature/issue 1255 admin view mobile fix #1255 fix #1178 fix #1251

### LINKED ISSUE #1178: admin page - move view scripting into controller
would be good to clean up the view here and do all the scripting in the controller and pass the results to the view: https://github.com/emoncms/emoncms/blob/master/Modules/admin/admin_main_view.php

@TrystanLea this could then allow us to create another view with the same code that would allow us to return the system settings in a json object  `/admin/system.json` ?

### LINKED ISSUE #1251: Download update log button missing
After latest updates to the update page the "download update log" button is missing. This button is very useful for users to download update log for support requests etc. 

Selection_153

### LINKED ISSUE #1255: Improve admin page mobile friendliness
Currently the admin page does not work too well on mobile view this could be improved by reducing the width of the log window
Screenshot_20190502-163856

### PR DESCRIPTION
**Pull request by emrysr**
fix issue #1255 - resize admin view for mobile
fix issue #1178 - move view scripting into controller
fix issue https://github.com/emoncms/emoncms/issues/1251 restore download log button

removed the `<table>` layout for a css row/column layout that can be re-arranged on smaller devices

small screen screenshot:
delwedd

### CODE REVIEW

**Comment by emrysr** [comment]
a little feature creep sorry. i've displayed the current logging level with the emoncms log viewer. I've also added the ability to edit the logging level within emoncms (if `settings.php` is writable)

screenshot showing log level above emoncms log:
image



@glynhudson - travis test fails on `sudo apt-get install php-pear...` line 671

this isn't something i've worked on ? can it be changed to allow the test to pass?

**Comment by emrysr** [comment]
thanks to @takkaria for the user popup notification script the group module https://github.com/emoncms/group

re used it here to notify users that data is copied to clipboard

**Comment by emrysr** [comment]
modified the `copy to clipboard` output format. doesn't use the markdown table format now. layed out with headings and list items.
also new endpoint available to view the server details as json object: `admin/system.json`

clicking individial lines in the server info now copies that line to the clipboard

**Comment by glynhudson** [comment]
Nice work looks great. I've just tested and all is working well. 

>A little feature creep sorry. I've displayed the current logging level admin/loglevel.json next to the emoncms log viewer on the admin page admin/view. I've also added the ability to edit the logging level within emoncms (if settings.php is writable)

Nice, that looks good. However, setting.php is not writeable. However, this would be very useful to edit log level for emonhub in the [config module](https://github.com/emoncms/config), i've opened an issue for this https://github.com/emoncms/config/issues/13

**Pull request merged**
