### PR TITLE
Feature/issue 655 clear all old feed data

### PR DESCRIPTION
**Pull request by emrysr**
fixes: #655 
also fixes: #878

this allows for clearing all feed data and "trimming" data up to a given date

image
column marked yellow = clear
column marked green = trim

**NOT YET TESTED ON A EMONPI.**

### CODE REVIEW

**Comment by emrysr** [comment]
I've added the column "Days" column during testing and didn't remember to remove it...
looks a lot like this: Add "first created" date to feeds #878 

I can remove the column from this pr and create a new one with that feature if required.

**Comment by emrysr** [comment]
Now shows success/error message in modal overlay once clear() or trim() is called.

 image

**Comment by emrysr** [comment]
@TrystanLea 
I've re-arranged the modal layout so that scrolling isn't needed to see all the options.
the success/fail message replaces the warning in the modal header.

image

**Comment by TrystanLea** [comment]
Fantastic! thanks @emrysr! really appreciate all the work you've put into this one

**Comment by emrysr** [comment]
added another feature to the feed trim form

relative date selection buttons
https://github.com/emoncms/emoncms/pull/946

**Comment by JacoFourie** [comment]
Hi. How do I get this option ? I am running 10.1.3

**Pull request merged**
