### PR TITLE
Adds support for named bulkInserts

### PR DESCRIPTION
**Pull request by fredrike**
eg. supports `input/bulk.json?data=[[-10,16,1137],[-8,17,{"1": 1437},{"2":3164}],[-6,19,{"data": 1412},{"anotherData":3077}]]` 

Solves #337.

### CODE REVIEW

**Comment by jeremypoulter** [comment]
This could add quite a large overhead for large datasets, it would be nice to only have to send the name once. That being said it i better than nothing so probably worth merging, especially on emoncms.org

**Comment by TrystanLea** [comment]
Sorry for the slow response on this. does it produce the following error for you:
PHP Warning:  strlen() expects parameter 1 to be string, object given in...

Perhaps amending to the following would be best:

if (is_object($item[$i])) {
    
} else if (strlen($item[$i])) {

}

**Comment by fredrike** [comment]
Sorry for being even slower on this..

the `continue;` on line [144](https://github.com/emoncms/emoncms/pull/615/files#diff-6f4cc2f54a9c2c476d95333d0d52da0dR144) actually skips the rest of the content in the for loop and it is included to not increment the `$name` variable so it should never reach the second `if`.

**Comment by TrystanLea** [comment]
Thanks @fredrike my turn to apologise again, great, is there any chance you could add this option to the input api documentation?

https://github.com/emoncms/emoncms/blob/master/Modules/input/Views/input_api.php

**Pull request merged**
