### PR TITLE
Process localization

### PR DESCRIPTION
**Pull request by thib66**

### CODE REVIEW

**Comment by thib66** [comment]
image
Modal process window now correctly translated when using French localization

**Comment by thib66** [comment]
image
Modal process window now correctly translated when using French localization (coming from virtual feed displayed in the Source page)

**Comment by thib66** [comment]
Once this PR validated, I will try to do changes in order to have the localization coming from js files

**Comment by TrystanLea** [comment]
Hello @thib66 sorry for the delay in the reply.

Is there a reason youve used 

    <h2><?php echo dgettext('process_messages','Process API'); ?></h2>

instead of

    <h2><?php echo _('Process API'); ?></h2>

surely that's already localisation ready?

the diff comparison on process_processlist.php is showing a completely changed file which makes difference tracking hard, is there any way you can change that?

**Comment by thib66** [comment]
Hello @TrystanLea ,
I used **_<h2><?php echo dgettext('process_messages','Process API'); ?></h2>_**
instead of
**_<h2><?php echo _('Process API'); ?></h2>_**
because the proccess window is displayed from **_emoncms/input/view_** web page.

**_emoncms/input/view_** web page loads : 
**_input\locale\fr_FR\LC_MESSAGES\messages.mo_** and **_input\locale\fr_FR\LC_MESSAGES\messages.po_** via **_input_menu.php_**
with the following code : 
    **_$domain = "messages";
    bindtextdomain($domain, "Modules/input/locale");
    bind_textdomain_codeset($domain, 'UTF-8');_**

As initially there were no localization for the process module, I decided to create the **_process\locale\fr_FR\LC_MESSAGES\messages.mo_** and **_process\locale\fr_FR\LC_MESSAGES\messages.po_** 

Process modal popup is displayed from **_emoncms/input/view_** web page and the process modal popup tries to load **_process\locale\fr_FR\LC_MESSAGES\messages.mo_** and **_process\locale\fr_FR\LC_MESSAGES\messages.po_** in order to create the "messages" domain but there is a conflict with "messages" domain already created with input web page.
That's why I needed to load a domain different from initial "messages" domain.

**Comment by thib66** [comment]
You have the same issue with the process windows displayed from feed web page when you want to configure a virtual node.

**_emoncms/feed/view web_** page loads :
**_feed\locale\fr_FR\LC_MESSAGES\messages.mo_** and f**_eed\locale\fr_FR\LC_MESSAGES\messages.po_** via **_feed_menu.php_**
with the following code :
**_$domain = "messages";
bindtextdomain($domain, "Modules/input/locale");
bind_textdomain_codeset($domain, 'UTF-8');_**

**Comment by thib66** [comment]
Concerning **_process_processlist.php_** additional localizations have been added and initial calls to "messages" domain have been modified to "process_message" domain

**Comment by thib66** [comment]
Hello @TrystanLea,
complete diff comparison concerning process_processlist.php should be available here : 
 https://github.com/thib66/emoncms/commit/36e8e007fb05015b8fb1085b71a3fc34576f02c7#diff-08a152d0db2b6db2c85616504a0309e5

**Comment by thib66** [comment]
Close PR due to master branch not updated on my github fork.

**Comment by Paul-Reed** [comment]
Aymeric, probably a bad time to start a Fork, as there has been some problems tonight with the Master branch. See posts at the end of this thread - https://community.openenergymonitor.org/t/updating-system-libraries-used-by-emoncms/6274/38

**Comment by thib66** [comment]
Ok. Hoping that new PR concerning copy to clipboard is not impacted

**Pull request closed without merging**
