### PR TITLE
Unbreak travis tests

### PR DESCRIPTION
**Pull request by reedy**
It seems the individual tests are failing on 5.6 and Chrome (that's a different issue), but I've mostly got your travis tests working so they run...

And they all pass on 7.2, and FF passes on 5.6

See https://travis-ci.org/reedy/emoncms/builds/551952830

image

### CODE REVIEW

**Comment by reedy** [comment]
Looks like your browser tests are kinda flaky...

Still. Better they're actually running rather than dying because of test setup issues

**Comment by reedy** [comment]
Passes in this PR but failed in my fork? Helpful :)

https://travis-ci.org/emoncms/emoncms/builds/551957855
https://travis-ci.org/reedy/emoncms/builds/551956996

**Comment by glynhudson** [comment]
Looks like an improvement, let's monitor how it gets on. Considering removing the browser tests. Seems trouble then it's worth

**Comment by reedy** [comment]
Browser tests can be pretty flaky... IF someone is interested in working on them, great. But if they're just rotting, they're not great to have around and just end up annoying people when they flap :)

**Comment by glynhudson** [comment]
Indeed, they keep failing randomly so most devs have stopped taking notice of the tests which is obviously not great!

**Pull request merged**
