### PR TITLE
Add support for secure mqtt connections

### PR DESCRIPTION
**Pull request by f4grx**
Hello,

this commit adds support for secure mqtt broker connections.

Thanks for merging.

### CODE REVIEW

**Comment by TrystanLea** [comment]
Thanks @f4grx thats great!

**Comment by TrystanLea** [comment]
I made a couple of small modifications after testing.

**Comment by borpin** [comment]
I would have expected an example setup in the `default.settings.ini` file. How will anyone know how to use it other wise?

**Comment by slorquet** [comment]
Sure. Do you require a pull request or can you just apply this?
```
diff --git a/default-settings.ini b/default-settings.ini
index 14b85e40..0b7201bc 100644
--- a/default-settings.ini
+++ b/default-settings.ini
@@ -54,6 +54,18 @@ user = ''
 password = ''
 basetopic = 'emon'
 client_id = 'emoncms'
+; secure MQTT parameters
+; capath must be defined to enable SSL usage.
+; This is the only setting required to connect to a SSL mqtt broker.
+;capath = '/etc/ssl/certs'
+; The following settigs are related to your CLIENT certificate, if your broker requires client authentication.
+; certpath must point to your client certificate
+;certpath = '/etc/letsencrypt/live/yoursite/fullkey.pem'
+; keypath must point to your client private key
+;keypath = '/etc/letsencrypt/live/yoursite/privatekey.pem'
+; keypw is the client private key password.
+; do not define if your private key is not password protected
+;keypw = ''


 ; Input
```

**Comment by TrystanLea** [comment]
Thanks @slorquet a pull request would be super helpful if possible, thanks

**Comment by slorquet** [comment]
Here it is
https://github.com/emoncms/emoncms/pull/1649

**Pull request merged**
