### PR TITLE
fixed the mqtt settings being saved to incorrect array

### PR DESCRIPTION
**Pull request by emrysr**
> # not fully tested !
> ## not ready for pulling into master!! 

@TrystanLea  I assume that these settings are not being used correctly or this issue would have been raised much sooner?...

### CODE REVIEW

**Comment by emrysr** [comment]
the array `$mqtt_server` is also created in these files so the incorrect settings would be overwritten
- /settings.php
- /emonpi.settings.php

**Comment by Paul-Reed** [comment]
It would be good to increment the $config_file_version in settings.php whenever an important change is introduced in settings.
This would force users to update their settings file.

**Comment by borpin** [comment]
>It would be good to increment the $config_file_version in settings.php whenever an important change is introduced in settings.
This would force users to update their settings file.

Even better would be a hierarchical system that would **not** require the whole setting file to be regenerated every time a change was made. #923 

I think the concern around having to do that is a block on users upgrading.

**Comment by Paul-Reed** [comment]
Yes. Have you seen https://github.com/emoncms/emoncms/pull/1010#issuecomment-426236385

**Pull request merged**
