### PR TITLE
Change 'Inputs' setup icon to avoid clash with with WiFi icon

### PR DESCRIPTION
**Pull request by glynhudson**
- Change 'Inputs' setup icon to avoid clash with with WiFi icon
- Minor bootstrap update (mainly docs URLS) V2.3.0 > V2.3.2

Before:

selection_030

After:

selection_029

### CODE REVIEW

**Comment by glynhudson** [comment]
Any objections to the icon change? I think the arrow icon is better suited?

**Comment by JonMurphy** [comment]
looks good to me!

**Comment by Paul-Reed** [comment]
Makes sense to have a different icon to the wifi icon.

Paul

**Comment by Paul-Reed** [comment]
Yes, the nightly php build needs to be disregarded.

**Comment by glynhudson** [comment]
> Yes, the nightly php build needs to be disregarded.

The nightly test has been removed :-) 

https://github.com/emoncms/emoncms/commit/efbc5e497f389e75b649c95f92b1f5679e6c71f1

https://github.com/emoncms/emoncms/commit/efbc5e497f389e75b649c95f92b1f5679e6c71f1

**Pull request merged**
