### PR TITLE
Add additional requirements

### PR DESCRIPTION
**Pull request by Twincarb**
Adds the requires to match those of the code content. redis not added as its not a required.

### CODE REVIEW

**Comment by reedy** [comment]
For reference in future when reviewing JSON... If GitHub shows a red/burgandy highlight, it's not valid
Screenshot 2020-04-29 at 19 40 04

**Comment by reedy** [comment]
>Adds the requires to match those of the code content. redis not added as its not a required.

You can use suggests for that https://getcomposer.org/doc/04-schema.md#suggest

**Comment by Twincarb** [comment]
Cheers @reedy I hovered over it but Github doesnt give a hint! If I had pushed from the desktop it would have had the comma, but I only copied and pasted before removing redis. 
Everydays a school day :)

**Comment by reedy** [comment]
Tools like https://jsonlint.com/ can be useful too :)

**Pull request merged**
