### PR TITLE
added requesting ip address to cookie not present log

### PR DESCRIPTION
**Pull request by emrysr**
adds requesting ip address to error log when cookie was not sent with incoming request.

writes to the log file in this format:
```
2020-01-20 10:26:35.178|INFO|rememberme_model.php|getCookieValues: not present for: 127.0.0.1
```
related to #1499 

more testing required on different hardware and OSes. Please comment here if this works or fails on your particular setup.

### TESTING:
the IP address will be written to the log file (`emoncms.log`) as an `INFO` message (log `level=1`)  if an attempt to login is made by a browser without a cookie set for your install of EmonCMS:-

1. set the log level to `1`(info)  in `settings.ini` to write the IP address to the logfile
2. clear cookies for the domain. [screenshot below](#clearing-cookies)
3. keep logfile changes open in a terminal window
```
$ tail -f /emoncms/emoncms.log
```
4. go to the login page the login page `http://localhost/emoncms/user/login` and watch for the changes in `emoncms.log`. The IP address should be shown as an `INFO` message.

### Clearing Cookies
[screenshot clearing cookies from a single website in chrome]
clear-cookies

### CODE REVIEW

**Comment by TrystanLea** [comment]
@xekon's issue relates to the user/login api specifically while this implementation appears linked to the remember me feature, perhaps the code to get the user ip address could be included as a function in emoncms/core.php and then logs included as part of these user/login checks:

https://github.com/emoncms/emoncms/blob/master/Modules/user/user_model.php#L385

and 

https://github.com/emoncms/emoncms/blob/master/Modules/user/user_model.php#L378

**Comment by xekon** [comment]
The idea is to ban any IPs that login incorrectly. If all that is needed to bypass this check is a modified cookie then its not a complete solution. I am hoping to ban anybody that attempts to use an incorrect username or password. This however is better than nothing and I can give it a try and report back.

**Comment by xekon** [comment]
Cool! will give this a try now!

**Comment by xekon** [comment]
I just pulled it down:
git pull origin pull/1506/head

my log is showing:
2020-01-23 00:58:22.152|INFO|rememberme_model.php|getCookieValues: not present for: 192.168.1.148

However it shows that same message, regardless if I enter the correct or incorrect password into the login form. I need a message that shows Only when incorrect password is used, that way I can create a fail2ban jail filter.

**Comment by TrystanLea** [comment]
Hello @xekon 

I've extended this here: https://github.com/emoncms/emoncms/commit/91f67090a8dbbed7734b0a714ddc0e4771ea0263

It now logs the ip address on invalid login attempts:

    2020-03-26 11:00:17.074|ERROR|user_model.php|Login: Incorrect password username:trystan ip:192.168.1.71
    2020-03-26 11:00:41.766|ERROR|user_model.php|change_password: old password incorect ip:192.168.1.71

**Comment by xekon** [comment]
Awesome! Thank You, can't wait to test it and setup a fail2ban jail.

**Comment by xekon** [comment]
During my security audit I realized I never finished this. It does work, here is the config I used:

`apt install fail2ban`

`nano /etc/fail2ban/filter.d/emoncms.conf`
```
[Definition]
failregex = .*Incorrect password username.*ip:<HOST>$
ignoreregex =
```

`nano /etc/fail2ban/jail.local`
```
[emoncms]
enabled = true
port = http,https
filter = emoncms
logpath = /var/log/emoncms/emoncms.log
maxretry = 1
bantime = -1
action = iptables-allports
```

**Pull request merged**
