### PR TITLE
Update PHPTimeSeries.php

### PR DESCRIPTION
**Pull request by arjenhiemstra**
In function get_data try to find the first valid data entry within the given timeframe and set $start to that time
This will 'sync' the start of the search through the dataset to the first real data entry. Preventing problems if $limitinterval = true and the passed &start   value is based on for example browser time.

### CODE REVIEW

**Comment by chaveiro** [comment]
with this change you set start time to the first timestamp on the engine, independent of specified start time.
After a few months of data you will get performance issues.

**Comment by arjenhiemstra** [comment]
Chaveiro, it is related to this forum post: http://openenergymonitor.org/emon/node/11720

For example vis. module zoom.php request a data set (5 years of data) with the start time of the request being the browser time. The database timestamps are based on 0:00 +- timezone offset. This leads to datapoint not being displayed.

I expected the added search to set the following search to the in data present startingpoint of the given timeframe. The following time entries in DB should then better fit the given interval and not cause the interval/2 test to fail (with as result no or limited data in graphs) 
Apparently this is not the case.

I did a small test with 3+ years of data, first without the new code, second example with. The second example shows less searches through the file on disk to find al the values in the given timeframe. I didn't test with a larger dataset so you are probably right.

No patch:
PHPTimeSeries.php|get_data feedid= 39 timestamp_in= 1291590000 timestamp_found= 1291590000 timestamp_end= 1449172805 number of searches= 1825

With patch:
PHPTimeSeries.php|get_data feedid= 39 timestamp_in= 1291590000 timestamp_found= 1353715200 timestamp_end= 1449172992 number of searches= 1106

**Comment by arjenhiemstra** [comment]
I've change $time to $start and changed the pull request.
Sorry for the error.

**Comment by arjenhiemstra** [comment]
Any thoughts on the proposed solutions in my forum post?
http://openenergymonitor.org/emon/node/11720

**Comment by chaveiro** [comment]
I can test this, but suppose it's ok now.

**Comment by arthurlutz** [comment]
am interested in this patch (for #403) but would rather prefer to get it with a new emoncms version. Any ideas on when that is planned ?

**Comment by arthurlutz** [comment]
sorry, got round to take a look at the patch, was so small I modified the line on my emoncms. It solves my problem! Thanks to all who have worked on this.

**Pull request merged**
