### PR TITLE
Consistent PSR2 formatting

### PR DESCRIPTION
**Pull request by Twincarb**
Formatted the files to PSR2 which makes them easier to read and maintain.
If this is accepted I will work through the other files in small batches.

### CODE REVIEW

**Comment by chaveiro** [comment]
I dont approve this kind of generic changes that do not add value at this phase of the project.
On the contrary it makes an headheak to merge and understand code changes from this point after due to major identation, spaces and line changes.

**Comment by borpin** [comment]
I suspect this may meet with some resistance, but I think it is a good thing. Poorly written and laid out code is far more prone to bugs and errors and whilst there may be some short term pain, the longer term gain makes it worth while IME.

**Comment by TrystanLea** [comment]
Thanks for the thought @Twincarb 

Im afraid I like a bit of flexibility in the way the code is formatted e.g:

    if ($apikey===false) { echo "User not found"; die; }

I know its probably not a popular view.. 

I think at the moment with everything else going on, its not a suitable time, although it always feels like we are running behind..

**Comment by Twincarb** [comment]
@TrystanLea not a problem, I just need to remember to disable the automatic PSR2 converter on any PR's I submit (not a problem on my windows box, just on the linux one!)

**Comment by TrystanLea** [comment]
Thanks @Twincarb

**Pull request closed without merging**
