### PR TITLE
Restored BarGraph Initial Zoom option

### PR DESCRIPTION
**Pull request by RDCH106**
Fix for https://github.com/emoncms/emoncms/pull/597

Discussion: https://github.com/emoncms/emoncms/pull/596

### CODE REVIEW

**Comment by RDCH106** [comment]
The initial zoom option is missing:

```
"bargraph":
    {
      "offsetx":0,"offsety":0,"width":400,"height":300,
      "menu":"Visualisations",
      "options":["feedid","colour","interval","units","dp","scale","delta"],
      "optionstype":["feedid","colour_picker","value","value","value","value","boolean"],
      "optionsname":[_Tr("Feed"),_Tr("Colour"),_Tr("Interval"),_Tr("units"),_Tr("dp"),_Tr("scale"),_Tr("delta")],
      "optionshint":[_Tr("Feed source"),_Tr("Line colour in hex. Blank is use default."),_Tr("Interval (seconds)-you can set \"d\" for day, \"m\" for month, or \"y\" for year"),_Tr("Units"),_Tr("Decimal points"),_Tr("Scale by"),_Tr("Show difference between each bar")],
      "html":""
    },
```

https://github.com/emoncms/emoncms/blob/master/Modules/vis/widget/vis_render.js

The commit was not reverted correctly  ¿?

**Comment by glynhudson** [comment]
Oh dear. Could you make a PR for this?

**Comment by RDCH106** [comment]
@glynhudson  Yes, I will do.

**Comment by RDCH106** [comment]
@glynhudson Done!

**Pull request merged**
