### PR TITLE
Update process_processlist.php

### PR DESCRIPTION
**Pull request by CidiRome**
Add Wh Accumulator that does not have a limit of 60Kw.

### CODE REVIEW

**Comment by TrystanLea** [comment]
Keeping this open for now as it's a nice addition but also keen not to add too many new processes at this point. 
Id like to review options to include process parameters separately somehow.

**Comment by chaveiro** [comment]
Fyi processes are modular, see scheduler module as example. 
For a module with processes just create a new module file at Module/modulename/modulename_process.php

**Comment by TrystanLea** [comment]
Good idea @chaveiro I've created a new module called processext and included this input process in that module. Thankyou @CidiRome for the contribution!

**Comment by TrystanLea** [comment]
Here's the link to the new module: https://github.com/emoncms/processext

**Pull request closed without merging**
