### PR TITLE
show status of running services on admin page

### PR DESCRIPTION
**Pull request by TrystanLea**
image

### CODE REVIEW

**Comment by borpin** [comment]
Would have been nice to have some discussion.  I'd have suggested that you need the output to tell you more for debugging purposes especially with SSH disabled.

Is it only those services?  service_runner?

**Comment by TrystanLea** [comment]
Sure, this is not complete yet, I was thinking the same regarding status output etc

**Comment by Paul-Reed** [comment]
Does it report the emonhub status for both versions of emonhub?
i.e. the emonpi version & pb's version as used in self builds.

**Comment by TrystanLea** [comment]
It tests for emonhub.py so should pick up both, https://github.com/emoncms/emoncms/commit/8540e01f3c402f4dc2f178f69c867774eb0ae260#diff-adef21b62b8a6ff7eecf2e8ebf361ab6R15

**Comment by Paul-Reed** [comment]
I've been trying the PR tonight, and found the following;
**Emonhub installed as per build guide -**
Correctly detects if running or not, but Start/Stop/Restart/Kill has no effect.
**Mqtt_input installed as per build guide -**
Start/Stop/Restart/Kill has no effect.

**Comment by glynhudson** [comment]
Awesome! Nice work. That looks like a really useful addition. I'll test on Monday

**Pull request merged**
