### PR TITLE
Update default settings and example setting

### PR DESCRIPTION
**Pull request by borpin**
Minor modifications to default settings

Add some items to example settings file.

### CODE REVIEW

**Comment by TrystanLea** [comment]
Thanks @borpin

**Comment by TrystanLea** [comment]
I've changed the default buffer time to 300s, it reduces write load a fair bit. The alternative would be to set it to longer here: https://github.com/openenergymonitor/EmonScripts/blob/master/defaults/emoncms/emonpi.settings.ini? and keep the default at 60?

**Comment by borpin** [comment]
> I've changed the default buffer time to 300s, it reduces write load a fair bit.

There has been discussion about this on the forum. I think it was different in different places but most recently I thought it has been 60. Might be worth checking with others.

I think a default of 60 and raise it for the emonpi might be the best route.

**Comment by TrystanLea** [comment]
Ok done:

https://github.com/emoncms/emoncms/commit/34d976db7f09b74ad17d86f234bc37edb3621834

and 

https://github.com/openenergymonitor/EmonScripts/commit/57cf3f3c683570cb5b472424333307705ad10536

**Pull request merged**
