### PR TITLE
Support for external themes

### PR DESCRIPTION
**Pull request by JSidrach**
If the $theme variable in settings.php is not "basic", it looks now for the path of the external theme (previously, it was ignored).

### CODE REVIEW

**Comment by chaveiro** [comment]
I think its better to reduce context of folder structure for themes to BasePath/Theme/ and move main theme to  :
    BasePath/Theme/default 
Support for others themes as sub folders,  like: 
    BasePath/Theme/other_theme_name 
Instead of just BasePath/some_theme_name.
What do you think?

**Comment by JSidrach** [comment]
I was putting the external themes on an absolute path, outside of emoncms,
but your proposal seems more reasonable.

This involves changing some code of the default theme too, as some paths
(images) load from there. It also requires changing some paths somewhere (I
am thinking of the login image, for example).

Finally, we should add some lines to the gitignore so it ignores everytheme
but the default (similar to what I did with Modules).
I can work on this today, do you mind?

**Comment by JSidrach** [comment]
Implemented in #379 . I have not renamed basic to default so the same default.settings.php will work without any change.

**Comment by chaveiro** [comment]
Cool, nice work.
It's looks better this way and will avoid confusion with folders role in future.

**Pull request merged**
