### PR TITLE
Merge Feature Branch into Master

### PR DESCRIPTION
**Pull request by Paul-Reed**
Adds 'copy system info' to clipboard for use in forum.

### CODE REVIEW

**Comment by Paul-Reed** [comment]
@thib66 Are you happy with the minor formatting changes made to your PR.
See the result of the changes https://community.openenergymonitor.org/t/copy-system-info-to-clipboard/6232/34

Paul

**Comment by thib66** [comment]
Hello Paul,
yes I am happy and  think that this improved feature will give satisfaction for most of people.
regards,
Aymeric

**Comment by Paul-Reed** [comment]
Nice work @thib66 
thank you.

Paul

**Comment by glynhudson** [comment]
Yes, thanks indeed @thib66. This is really great 👍

**Pull request merged**
