### PR TITLE
Fixes to feed get data with mode=daily|weekly|monthly

### PR DESCRIPTION
**Pull request by hagai-shatz**
Feed API data.json with mode=daily|weekly|monthly is designed for cumulative feeds and is only supported by PHPFina and PHPTimeSeries engines. However, both engines do not fully support it. 
For PHPFina: this fix enable to return a value even if the value at midnight is null, by looking back to the latest valid value.
For PHPTimeSeries: this fix enable to return "weekly" and "monthly" modes.

### CODE REVIEW

**Comment by Paul-Reed** [comment]
This looks a nice improvement, thanks Hagai.
@chaveiro I would value your opinion.

Paul

**Comment by TrystanLea** [comment]
Sorry for the slow reply on this. The PHPTimeSeries changes look great happy to merge these. For PHPFina the midnight null value issue is designed to be avoided by using the power_to_kwh or wh_accumuator input processor which join across missing values as these are cumulative type feeds.

That said I would be happy to accept this change if there is a limit to how far back or forward from midnight it tries to find a valid value, it look like at the moment it could try and scan through a large number of datapoints, perhaps it could be limited to scanning back 30 minutes from midnight?

**Comment by hagai-shatz** [comment]
@TrystanLea Are you sure the power_to_kwh or wh_accumuator will solve the problem? If there is no power transmitted to the input during midnight, the processor will not run and will not generate a value in the feed.
As for the lookback limit - it is only go back until the last interval (day/week/month) and no more than the absolute total reads set in the service - 10000.
I will not expect it to read back more than a few values. However, in my feeds, I'm importing data from a Solaredge inverter that does not provide any values when there is no sun so the lookback might be for a few hours in a feed with 5 minutes interval, that is 12 reads per hour to look back at the last value of the day.

**Comment by Paul-Reed** [comment]
Any update pls @TrystanLea 

Thanks
Paul

**Comment by TrystanLea** [comment]
Hello @hagai-shatz apologies for my slow reply, a few too many things on in parallel as usual, power_to_kwh or wh_accumuator will solve this issue for PHPFina as the missing data is filled on post, This is handled here: https://github.com/emoncms/emoncms/blob/master/Modules/feed/engine/PHPFina.php#L217 if join mode is disabled it enters null otherwise it joins with valid datapoints.

**Comment by TrystanLea** [comment]
Very happy to merge the changes to PHPTimeSeries if you could send me this separately.
Thanks a lot and apologies again for the delay
Trystan

**Comment by TrystanLea** [comment]
I've merged the PHPTimeSeries changes in manually, see: https://github.com/emoncms/emoncms/commit/c116b96b95be17f6fadb05c3beff41599bba1afc

**Pull request closed without merging**
