### PR TITLE
Process localization and french localization for this module

### PR DESCRIPTION
**Pull request by thib66**

### CODE REVIEW

**Comment by thib66** [comment]
Hello,
please see comments for #756 
Regards,
Aymeric

**Comment by Paul-Reed** [comment]
@TrystanLea made a comment about this in #756 so awaiting his consideration.

Paul

**Comment by thib66** [comment]
Hello,
do you need further information /details in order to validate the PR?
Thanks for your answer.
Regards,
Aymeric

**Comment by TrystanLea** [comment]
Thanks @thib66 that's a much clearer and easier to review pull request, much appreciated, tested here works fine.

**Pull request merged**
