### PR TITLE
Add UUID

### PR DESCRIPTION
**Pull request by alexandrecuer**
iintegration of a guidv4 function in the core and modification of user model and controller

uuid for a user is generated at user creation or the first time the `user/getuuid.json` route is called after the database update

the route returns a json output : 
```
{
    "success": false or true, 
    "message": error message or uuid string
}
```

### CODE REVIEW

**Comment by chaveiro** [comment]
What is the usecase for this?

**Comment by alexandrecuer** [comment]
> What is the usecase for this?

providing unique identifier when emoncms is used with home assistant : cf https://developers.home-assistant.io/docs/entity_registry_index/

**Comment by chaveiro** [comment]
> > What is the usecase for this?
> 
> providing unique identifier when emoncms is used with home assistant : cf https://developers.home-assistant.io/docs/entity_registry_index/

Isn't the email of the account a valid unique id, for the matter?

**Comment by TrystanLea** [comment]
We've been discussing this in a PM will add you. @alexandrecuer is trying his best to improve HA integration 👍

**Comment by borpin** [comment]
> Isn't the email of the account a valid unique id, for the matter?

No, you can have several users with the same email address.

**Comment by alexandrecuer** [comment]
I've packaged a small python library on pypi which should produce all datas in the home-assistant flavour :
https://pypi.org/project/pyemoncms/

**Comment by alexandrecuer** [comment]
seems to be ready, could be nice to have some testing and feedback :-)

the testing procedure seems a little scary, really sorry

# step 1

create a `/data` folder on the host

run an emoncms standalone container with persistent datas
```
sudo docker run --rm -p 8081:80 -p 7883:1883 -v /data:/data -it alexjunk/emoncms
```
create the first user

download a user less dataset, eg : `wget https://github.com/alexandrecuer/smartgrid/raw/master/datasets/no_user_table/bloch-2021.tar.gz`

restore it

At this stage you have an emoncms sensor without uuid

# step 2

download visual studio code, fork https://github.com/home-assistant/core to your github account

go to https://developers.home-assistant.io/docs/development_environment

paste your fork url into the input text box and click open

image

your home assistant dev container will start

open configuration.yaml and add the emoncms integration :

```
sensor:
  - platform: emoncms
    api_key: your_emoncms_key
    scan_interval: 10
    url: http://your_emoncms_url:8081
    id: 1
```
Hit F5 to start home assistant

You should see emoncms data on your dashboard

to publish some fresh datas :

```
mosquitto_pub -h your_emoncms_url -p 7883 -u "emonpi" -P "emonpimqtt2016" -t 'emon/OWM/outdoor_temp' -m 43.2
```

# step 3 - import the new version of the integration in your dev container

```
git remote set-url origin https://github.com/alexandrecuer/core.git
git checkout 2024-06-09
```

restart home assistant

you should see in the ha logs a message reporting no uuid available - migrate your emoncms sensor to a newer version

# step 4 - test a new version of emoncms

stop home assistant and stop the emoncms container
```
git clone -b add_uuid http://github.com/alexandrecuer/emoncms
```
cd emoncms

```
sudo docker run --rm -p 8081:80 -p 7883:1883 -v $(pwd)/core.php:/var/www/emoncms/core.php -v $(pwd)/Modules/user:/var/www/emoncms/Modules/user -v $(pwd)/Modules/feed:/var/www/emoncms/Modules/feed -v /data:/data -it alexjunk/emoncms
```
login to emoncms and migrate the database

restart home assistant

**Comment by alexandrecuer** [comment]
Thanks Trystan :-)
new container is available : 
```
docker pull alexjunk/emoncms:alpine3.19.1_emoncms11.5.7
```

**Comment by TrystanLea** [comment]
Thanks @alexandrecuer !

**Pull request merged**
