### PR TITLE
ISC Konstanz contribution

### PR DESCRIPTION
**Pull request by adminde**
Hi guys,

I wanted to commit some hopefully useful things that come in a bundle with other pull requests I'm creating right now, hence I summarized some things in a [forum thread](https://community.openenergymonitor.org/t/isc-konstanz-summer-contributions/)

This pull-request consist of mainly small changes like fixed indents and systax for the new `input_view.php/.js` and `feedlist_view.php`. Generally, I tried to improve the javascript code consistency a little to use more camelCase, as conventions encourage. I additionally changed the collapse-indicators to be chevron icons, as I simply preferred those visually.
Also, I improved the themes' style sheet functionalities a little. E.g. to make less use of `!important` (still a lot though) and include a few things such as the color of top affix background color in the new views.

As we added a total of 3 new menu entries, I increased the menu order values of most modules, as I arrogantly didn't like the input menu `order => 0` :)

Further, the sidebar now allows to be differently colored, depending on the theme used:

emoncms-app-standard

emoncms-app-blue|690x327

emoncms-app-sun|690x325 

At last, I updated the MysqlTimeseries to include some new features, as we use those feeds as a shared resource e.g. for forecasts and EMS a lot.
To improve this, we simply added the possibility to optionally use a separate database for the mysql feeds, configurable via the `settings.php`:

    $feed_settings = array(
        'mysql'=>array(
            'prefix' => 'feed_',
            'generic' => true,
            'database' => 'emondata',
            'username' => 'emondata',
            'password' => '<password>'
        )
    );

If nothing is configured, the engine will behave as before.
Additionally, a different prefix can be configured. Alternatively, by setting *generic* and optionally *prefix* **false**, the feed table name may be configured in the inputs process configuration dialog.

### CODE REVIEW

**Comment by adminde** [comment]
I just slimmed this PR a little down.
The MysqlTimeseries feature can now be found in #1420 and I generally removed some outdated changes to the input and feed views.

**Comment by adminde** [comment]
Hei guys, sorry again for this long delay for me to continue with these pull requests...

I merged all new commits now and updated my PRs for the [graph](https://github.com/emoncms/graph/pull/97/files) and the [app](https://github.com/emoncms/app/pull/97) modules.
Most invasive change in these 3 is definitly the light sidebar version, which I still very much hope is something you do not dislike or even planned yourself to do :)

**Comment by TrystanLea** [comment]
Thanks for updating this pull request @adminde 

Im keen to keep the dark sidebar Im afraid. Is there a way we can make this a selectable option in the theme?

**Comment by TrystanLea** [comment]
Hello @adminde Im going to try and support your suggested colour schemes in my review of emoncms css and layouts as discussed here https://github.com/emoncms/emoncms/issues/1661. Closing this for now with the intention of taking inspiration from your ideas as part of this review.

**Pull request closed without merging**
