### PR TITLE
Localization 04 11 2021

### PR DESCRIPTION
**Pull request by thib66**
Add localizations

### CODE REVIEW

**Comment by TrystanLea** [comment]
Thanks @thib66

**Comment by TrystanLea** [comment]
Interested to hear if you get any issues testing the latest master with my changes here https://github.com/emoncms/emoncms/issues/1744

**Comment by TrystanLea** [comment]
you will need the latest master for the app, dashboard and graph modules as well

**Comment by thib66** [comment]
Hello Trystan, may you have a look at https://github.com/emoncms/dashboard/pull/276 in order that I can retrieve the latest master for dashboard with the pull request included? Thanks in advance, regards

**Pull request merged**
