### PR TITLE
bookmarkable saved graphs

### PR DESCRIPTION
**Pull request by emrysr**
related to graph repo pull request: https://github.com/emoncms/graph#96

added bookmark edit link hover text
check for url hash fragment in js
added translatable string to bookmarks.php "edit"
added user bookmarks to <script> tag in sidebar

### CODE REVIEW

**Comment by emrysr** [comment]
https://github.com/emoncms/graph/pull/96

**Comment by TrystanLea** [comment]
Testing here there is an issue navigating back in the graph menu when a saved graph bookmark is selected. There also does not appear to be a difference between the master and feature branch behaviour, have our recent commits got in the way?

**Comment by TrystanLea** [comment]
@emrysr not sure if my reply above got through?

**Comment by emrysr** [comment]
@TrystanLea  - i've corrected the merge conflict.
this is related to a graph repo pull request: https://github.com/emoncms/graph/pull/96

The bookmark system wasn't able to process links with a hash symbol
eg `/controller/action#name=value`. The bookmarks wouldn't match as the hash portion of the url isn't sent to the server (or php).

Works with js now.

**Comment by TrystanLea** [comment]
Thanks @emrysr it does still seem to be an issue. When I select a saved graph I cant navigate back.. Im also getting this error now:

image

**Comment by TrystanLea** [comment]
Im getting an error when attempting to navigate top menu while testing this

image

**Pull request merged**
