### PR TITLE
Add mode for strict JSON input parsing.

### LINKED ISSUE #641: post.json incompatible with JSON produced by Python
In particular, Python's `json` module typically includes spaces between components of its output.  A typical return value from `json.dumps` might be

    {"vrms": 245.12, "pulse": 1, "temp3": 300, "temp2": 300, "temp1": 300, "temp6": 300, "temp5": 300, "temp4": 300, "rssi": "-27", "power4": 0, "power3": 0, "power2": 0, "power1": 384}

In this case, emoncms splits the key/value on the ':', but this means that the space between the comma and the key for all but the first value is included in the key itself and new inputs are created with a space at the beginning of their name (which you can't actually see in the rendered output).

This doesn't affect use of emoncms with the built in utilities because for pushing groups of values normally they're either posted sequentially (using the nodevars format) or in the bulk format.  However, `post.json` claims to be able to take input of this form, and by adding it we can improve handling of input from other sources.

### PR DESCRIPTION
**Pull request by adpeace**
Fixes #641 

This pull request replaces the previous one that added a `trim` around the keys to avoid a problem where parsing could introduce additional spaces in the input names.

The approach here is to add a new input field `fulljson` ('full' meaning 'parsed with full json parser') that is parsed differently (using `json_decode`) and leaving the other input fields as-is (parsed using the old string-splitting method).

The change also adds a check for the input having been valid before attempting to process it that was previously missing - this avoids a situation where PHP raises errors because the contents of `$data` were not of the expected type to iterate over.

### CODE REVIEW

**Comment by TrystanLea** [comment]
Great, works well! Could you remove the printing of $datain on failure to decode? From what I understand doing so like this can create a security issue.

http://localhost/master/input/post.json?node=1&fulljson="test"
this input also passed the $valid test giving the following error:

<br />
<b>Warning</b>:  Invalid argument supplied for foreach() in <b>/var/www/master/Modules/input/input_controller.php</b> on line <b>269</b><br />
ok

**Comment by adpeace** [comment]
Updated the branch.

**Comment by glynhudson** [comment]
Thanks a lot, very sorry so long to merge this. 

Would it be possible to add the new fulljson API with an example to the input API helper page: 

https://github.com/emoncms/emoncms/blob/master/Modules/input/Views/input_api.php

**Comment by adpeace** [comment]
Hi; yes, I'd be happy to add an entry on that page, I can submit a PR in the next couple of days.  The example you gave isn't quite right: the `fulljson` is the name of the parameter, not the object (i.e. `post.json?node=1&fulljson=...`).

**Comment by glynhudson** [comment]
Thanks! Ah yes, the following fulljson post works great :100: 

http://emonpi/emoncms/input/post.json?node=1&fulljson={"power1":1100,"power2":2100,"power3":3100}

**Pull request merged**
