### PR TITLE
Feature/issue 1038 move feed list buttons bottom

### LINKED ISSUE #1038: Feeds page buttons at both top and bottom of page
Should all the butttons be grouped together rather than split between the start and the end of the page?

Style wise the "create new virtual feed" button could be reduced to a "+" button with a more informative hover-over like the new "select all" etc. Likewise the "refresh feed size" could be reduced to refresh symbol. 

(See https://community.openenergymonitor.org/t/thoughts-on-the-new-input-and-feed-page-layouts/8583?u=pb66)

### PR DESCRIPTION
**Pull request by emrysr**
fix #1038 

There was just enough room for 2 more buttons in the mobile view: 
image

### CODE REVIEW

**Comment by emrysr** [comment]
As @pb66 's suggestion I've added a dropdown list of buttons for the mobile version:

image

not sure if this is as useful as the previous version, however there is now no wrap of buttons using smaller devices.

The desktop (wider screen) version still has the fixed toolbar at the top when scrolling down a longer list:
image

**Comment by emrysr** [comment]
the desktop view now also has a separator between the buttons:
image

**Comment by TrystanLea** [comment]
Sorry for the delay on this, I think we should keep as is. The dropdown menu makes the interface feel a bit more cumbersome. I think keeping the less used refresh and add virtual feed button at the bottom keeps things clean. Can I close the pull request so that we move forward as is for now?

**Comment by TrystanLea** [comment]
PS: Thanks for your work putting this concept together @emrysr as we've discussed :)

**Pull request closed without merging**
