### PR TITLE
added short_name to processlist array

### PR DESCRIPTION
**Pull request by emrysr**
am still working on this. uploaded for you to see progress.

@trystan I'm going to use the json file format to store process descriptions as per our dm discussion

having one place describe the processlist will make it easier to read the same information from js and php

associated to issue #744

### CODE REVIEW

**Comment by TrystanLea** [comment]
Thanks @emrysr I think we might as well load the json processlist via php as there are multiple processlist.json files, one for each module: process, eventp & schedule. Doing it via the php loader would also allow for validation etc

**Comment by emrysr** [comment]
ok - thanks

**Comment by emrysr** [comment]
@trystan - this work on this branch is finished for now. you can review and merge if you want.

I'll be working on the branch processlist_refactor on the rest of this work

**Comment by TrystanLea** [comment]
this is merged into the processlist_refactor branch

**Pull request closed without merging**
