### PR TITLE
Copy2clipboard

### PR DESCRIPTION
**Pull request by thib66**

### CODE REVIEW

**Comment by Paul-Reed** [comment]
Merged to branch `copy2clipboardv2`

Thanks Aymeric

**Comment by Paul-Reed** [comment]
Aymeric, I think it's missing a line break.

table2

Without it, the Markdown table is not displayed correctly.

table1

Paul

**Comment by thib66** [comment]
Hello, probably.
How can I do a new pull request now that the branch is merged?
Regards,
Aymeric

**Comment by Paul-Reed** [comment]
Make a fork of emoncms as usual, then in your fork, select the `copy2clipboardv2` branch, make your changes & submit a PR.

Paul

**Comment by thib66** [comment]
Hello,
I think I cannot since #781 is not actually merged and in I believe I cannot create a second parallel fork with my profile. Regards, Aymeric

**Comment by Paul-Reed** [comment]
...or alternatively, I can add it on your behalf? I assume it's an addition to line 393;
`copyTextToClipboard('<details><summary>SERVER INFORMATION</summary><pre>\n'+ '| | | |\n' + '| --- | --- | --- |' +serverInfoDetails + '</pre></details>\n<details><summary>CLIENT INFORMATION</summary><pre>\n'+ '| | | |\n' + '| --- | --- | --- |' + clientInfoDetails + '\n</pre></details>');`

Paul

**Comment by thib66** [comment]
yes adding a second line break after the two <pre> tag should solve the issue.

**Comment by Paul-Reed** [comment]
That's looking good Aymeric, thank you.
I've updated the forum post accordingly.

Paul

**Pull request merged**
