### PR TITLE
UTF-8 support

### PR DESCRIPTION
**Pull request by JSidrach**
- Fixed regex expressions to support utf-8 characters
- Fixed a security bug where the $tag parameter on input_mode.php was not being sanitized
- Set charset to utf-8 in the database connection

It should fix the issue #369

### CODE REVIEW

**Comment by tgmaxx** [comment]
This commit caused all of my inputs that have underscores in their names to stop working. I reverted to previous commit and they are working again, so this update has some issues.

**Comment by JSidrach** [comment]
Taking a look at this... sorry for the inconvenience.

**Comment by tgmaxx** [comment]
To be clear, by input names, I mean input "key" names.
Thanks!

**Comment by JSidrach** [comment]
I found the issue. Turns out in regexps, \w means letters+numbers+underscores... I thought it did not include underscores, so I replaced it with \p{N}\p{L} (unicode numbers and letters). It should be an easy fix, so I'll upload it as soon as possible.

**Comment by JSidrach** [comment]
Should be fixed by #383. Please reply here if the issue persists. Thanks for finding out this one!

**Comment by tgmaxx** [comment]
Ok no problem. Thanks for all of your work.

**Pull request merged**
