### PR TITLE
Include the received JSON string in error message

### PR DESCRIPTION
**Pull request by borpin**
As title.

### CODE REVIEW

**Comment by TrystanLea** [comment]
Thanks @borpin what is the reason for this change? The user already has access to the JSON string sent what does returning it achieve?

I think its also best practice to sanitise user input before printing it back, not sure what harm it would do in this case but a little weary of causing an unexpected issue.

**Comment by borpin** [comment]
It is a debugging help. All you get when it fails is 'false' - sending back what was received would help to debug issues. Alternative is to make the log message include more information. Again usually just says 'failed'.

**Comment by TrystanLea** [comment]
How about writing it to the emoncms log instead?

**Comment by borpin** [comment]
That would be helpful.

**Comment by TrystanLea** [comment]
I've added in a log of the invalid json https://github.com/emoncms/emoncms/commit/611fd01be39052b6aa5688ce9215aae0d428f795

**Pull request closed without merging**
