### PR TITLE
changes from https://github.com/emoncms/emoncms/pull/822

### PR DESCRIPTION
**Pull request by TrystanLea**
See original https://github.com/emoncms/emoncms/pull/822

### CODE REVIEW

**Comment by borpin** [comment]
I think it is worth keeping the warning that a connection attempt has been made.

The publish needs to check for a connection else that will raise an exception (not part of my original!).

**Comment by TrystanLea** [comment]
> I think it is worth keeping the warning that a connection attempt has been made.

Did I remove a warning?

**Comment by borpin** [comment]
>Did I remove a warning?

Ah, sorry, I didn't notice you had moved it.  Makes more sense to do it before the actual attempt.

>Let me know if there are any modifications I need to make?

https://github.com/emoncms/emoncms/blob/776384d9ece35468cc08750356f0a9fc688443ba/scripts/phpmqtt_input.php#L143
Strictly this should be 'Loop through all topics with data to publish' - queue implies more than one value for each topic.

https://github.com/emoncms/emoncms/blob/776384d9ece35468cc08750356f0a9fc688443ba/scripts/phpmqtt_input.php#L144-L148

Not able to do it myself from here (or more accurately don't know how to do it in the web interface) but it really needs a 'connected' check before line 144.

```php
if ($connected) {
    $publish_to_mqtt = $redis->hgetall("publish_to_mqtt"); 
    foreach ($publish_to_mqtt as $topic=>$value) { 
         $redis->hdel("publish_to_mqtt",$topic); 
         $mqtt_client->publish($topic, $value); 
    }
}
```
Looks good!

**Comment by borpin** [comment]
@TrystanLea You didn't make the change I suggested above and add in a 'connected' check before publishing.

**Comment by TrystanLea** [comment]
aha, ok will add that in

**Comment by TrystanLea** [comment]
Added in https://github.com/emoncms/emoncms/commit/aa97e9064ed1aec5ddf982923885b568ca8b62e9 thanks @borpin

**Pull request merged**
