### PR TITLE
Minor UI tweeks

### PR DESCRIPTION
**Pull request by chaveiro**

### CODE REVIEW

**Comment by TrystanLea** [comment]
Thanks @chaveiro Could you add screenshots of the effect of the changes?

**Comment by chaveiro** [comment]
Removes the space on feeds header and makes visible a x to close the menu.

**Comment by TrystanLea** [comment]
Unfortunately your pull request from a couple of days ago seems to have broken something on the inputs page:

image

Theres no padding between the chevron and the node name, and the time & value columns are also much closer together.

I think it's probably best that I revert those changes and we can look at that part again?

**Comment by TrystanLea** [comment]
I think I had better revert the feed list view changes as well, we spent a lot of time getting those to work and it's easy to break the styling so I think a more careful approach is needed on these visual elements

**Comment by TrystanLea** [comment]
I've created a pull request to revert the input and feed list view changes:
 https://github.com/emoncms/emoncms/pull/1668

Im not sure what issue the proposed changes intended to solve, screenshots of before and after would be really helpful. Perhaps there is a difference in browser rendering between what you are seeing and what I see?

**Comment by TrystanLea** [comment]
For this particular pull request, the divider is important in my opinion and Im not clear what the other changes aim to fix, I think we need to start again on these input and feed list changes and have a clearer process so that it's clear what the issues are and what the fixes are doing.

**Comment by TrystanLea** [comment]
I've created another pull request here that is based on the reverted branch that fixes a resizing issue with the original input list see https://github.com/emoncms/emoncms/pull/1669

**Comment by chaveiro** [comment]
The problem that my other commit fixed was that i have input ids as macaddress.  12 chars length and without the fix they make the table unreadable on small devices.

**Comment by chaveiro** [comment]
Chevron fix above

**Comment by TrystanLea** [comment]
Thanks @chaveiro can you show a screenshot of what the macaddress bug looked like? I will try and replicate here

**Comment by chaveiro** [comment]
Result:
image

**Comment by TrystanLea** [comment]
Thanks, what was the reason for adding in the dev col widths? why was it not possible to just use the existing object?

**Comment by chaveiro** [comment]
It would made the detail columns (1 or 2 chars on the example above) the size of the mac, so the name would not fit with the time since last read.

**Comment by TrystanLea** [comment]
Sorry @chaveiro it looks like you have added another set of commits to sidebar.js I cant merge pull requests without clear explanations of the changes and a more broken down explained process. What I really want is you to explain to me as if you are trying to explain to me how to fix it.

Im also working on a new sidebar version that replaces all of this anyway https://github.com/emoncms/emoncms/pull/1655

**Comment by TrystanLea** [comment]
I'm working through the input and feed list changes at the moment.

I've gone back a few steps and now working through your original pull request to try and understand the changes, applying them selectively, here are the nowrap class additions that you added in:

https://github.com/emoncms/emoncms/commit/61b32ddda84d65f2e6732e6a96940e5cf0d146fa#diff-4d7b3b5278305e5323d3f95a660c24f9aefa7d9f15ee2c6abb7a68c8a85240a1

**Comment by TrystanLea** [comment]
I've added in your lines that took into account the node description length in the width calculation but have not yet added in the separate treatment of the node heading section vs the inputs part. I cant quite work out the effect yet of the changes to the offsets added to the string lengths that you proposed. Im keeping those in mind, will review them on another system I have here with a larger variation in inputs etc.

https://github.com/emoncms/emoncms/commit/4efbd9e9c43c33573d68783770b8cacf3b7ce335

Im can see now a bit clearer the intention behind the 'dev' widths and will consider adding those in.

I have not yet made sense of your proposed change to the section that was hiding and showing the columns:

From:

    var columnsWidth = 0
    for (k in keys) {
        let key = keys[k]
        columnsWidth += col_max[key];
        hidden[key] = columnsWidth > rowWidth;
    }
    
    for (var key in hidden) {
        if (hidden[key]) {
            app.col[key] = 0;
            app.col_h[key] = 0;
        } else {
            app.col[key] = col_max[key]
            app.col_h[key] = 'auto';
        }
    }

to:

    var columnsWidth = 0
    for (k in keys) {
        var key = keys[k]
        if  (columnsWidth + col_max[key] > rowWidth){
            var dif = rowWidth - columnsWidth;
            columnsWidth += dif;
            if (dif => 0) {
                app.col[key] = dif;
            }
        } else {
            app.col[key] = col_max[key]
            columnsWidth += col_max[key];
        }
    }
```

it seems to cut with width of the process list down hiding parts of it before the column disappears...

**Comment by chaveiro** [comment]
Thats it.

**Comment by chaveiro** [comment]
The sidebar fix is to trigger a resize for the body to adjust to the size free/ocupied by the closed/opened sidebar  menu.

**Comment by chaveiro** [comment]
Every new commit with the github desktop app goes to the previous open commit on the origir repo.

**Comment by TrystanLea** [comment]
Yes I see what's happening, I think that's why its best to create a branch for the specific change and create a pull request from that. You can then create another branch for the next change and continue on that breaking it up into a series of pull requests based on the previous branch.

I read this contributor guidelines page for normalize.css the other day and thought it was quite good:
https://github.com/necolas/normalize.css/blob/master/CONTRIBUTING.md

**Comment by chaveiro** [comment]
So will you merge or accept this commit?

**Comment by TrystanLea** [comment]
Sorry @chaveiro I wont be merging this one. I mentioned before that I have the menu_v3 branch in progress and this pull request contains changes to the existing menu system and so will end up causing conflicts during the merge process, those files are replaced and removed completely. Im also looking for pull requests that are split up into feature branches e.g as discussed in https://github.com/necolas/normalize.css/blob/master/CONTRIBUTING.md as an example. I will close this for now.

**Comment by TrystanLea** [comment]
If you are able to reopen using specific feature branches for each self contained set of changes I will consider each in turn, this might be for example:

- Admin menu changes
- feed list view changes
- sidebar changes (if needed, please test on menu_v3 branch for any sidebar related changes)

Thankyou for at least trying to contribute and improve the project. I appreciate it. I just need a few things in place to make the process work and to help me maintain the project.

**Comment by chaveiro** [comment]
Maybe your future changes solve this commit later on and ignore altogether the need i had to fix it.
I've very few time available to rework further on this currently. Im sorry.

**Pull request closed without merging**
