### PR TITLE
Menu v3 (Still in development)

### PR DESCRIPTION
**Pull request by TrystanLea**
A refactoring of the emoncms menu system to simplify. 

Includes a different visual appearance for 3rd level menu's, such as the feed list in the graph module:

image

Work is ongoing, not to be merged just yet.

**menu_v3 module branches**

- https://github.com/emoncms/dashboard/tree/menu_v3
- https://github.com/emoncms/graph/tree/menu_v3
- https://github.com/emoncms/app/tree/menu_v3
- https://github.com/emoncms/config/tree/menu_v3
- https://github.com/emoncms/wifi/tree/menu_v3
- https://github.com/emoncms/sync/tree/menu_v3
- https://github.com/emoncms/postprocess/tree/menu_v3
- https://github.com/emoncms/backup/tree/menu_v3
- https://github.com/emoncms/demandshaper/tree/menu_v3

### CODE REVIEW

**Comment by borpin** [comment]
Much better.

**Comment by borpin** [comment]
Can you add in a way to reset the graph to 'blank'. Only way is to navigate away and come back presently.

**Comment by TrystanLea** [comment]
Thanks @borpin, I've added a Clear All button in there:

image

**Comment by chaveiro** [comment]
Untested but looks nice!

**Comment by TrystanLea** [comment]
Thanks @chaveiro, I think it still needs a bit more polish to get it to work really well, but its mostly there.

**Comment by TrystanLea** [comment]
Im removing the bookmarks feature with this update, the original intention was to create an easy way to have a single sidebar menu that linked to e.g the app, dashboard and demandshaper device that you might use most often. In the end I think the feature just complicates the navigation

**Comment by chaveiro** [comment]
Why not put that bookmark to the start icon on the above right menu, as a module?
It seems simples enough to do it in a few minutes.
Just need to have a new module called bookmark with all default modules php code files and a bookmark_menu.php to enable it automatically.

**Comment by TrystanLea** [comment]
Thats an interesting possibility, certainly open to a optional module implementation of the bookmark feature.

**Comment by chaveiro** [comment]
It could have been done as a module since the beginning anyway.

**Comment by alexandrecuer** [comment]
on a fresh installation, having this on the inputs list

emoncms

**Comment by TrystanLea** [comment]
Thanks Alex, there seems to be a cache issue with this bug, could you try reloading the page completely, il try increasing the js version to force cache reload later

**Comment by alexandrecuer** [comment]
you are absolutely right Trystan : it is a caching problem
thanks
the menu v3 is really nice :-) great job

**Pull request merged**
