### PR TITLE
Fix deprecated creation of dynamic property

### LINKED ISSUE #1837: Deprecation warnings when using PHP 8.2
Deprecation warnings are shown when PHP 8.2 is used.

```html
<b>Deprecated</b>:  Creation of dynamic property InputMethods::$user is deprecated in <b>/srv/http/emoncms/Modules/input/input_methods.php</b> on line <b>26</b><br />
<br />
<b>Deprecated</b>:  Creation of dynamic property InputMethods::$input is deprecated in <b>/srv/http/emoncms/Modules/input/input_methods.php</b> on line <b>27</b><br />
<br />
<b>Deprecated</b>:  Creation of dynamic property InputMethods::$process is deprecated in <b>/srv/http/emoncms/Modules/input/input_methods.php</b> on line <b>29</b><br />
<br />
<b>Deprecated</b>:  Creation of dynamic property InputMethods::$device is deprecated in <b>/srv/http/emoncms/Modules/input/input_methods.php</b> on line <b>30</b><br />
```

### PR DESCRIPTION
**Pull request by treiher**
Fixes #1837

### CODE REVIEW

**Comment by borpin** [comment]
We need to install PHP8.0 for ARMv6 devices. Does this work with PHP8.0?

**Comment by treiher** [comment]
This PR just adds some declarations of class properties. The code should also work with PHP 8.0.

**Comment by mattheworres** [comment]
@borpin can confirm it works on PHP 8.2. No reason it wouldn't work on PHP 8.0 - it will work on PHP 7.4, but it becomes an issue with PHP 8.1 or higher because that's when PHP marks it as a deprecation and it causes output buffer errors that stall the app in different locations.

**Comment by TrystanLea** [comment]
Thanks

**Pull request merged**
