### PR TITLE
Update input_api.php

### PR DESCRIPTION
**Pull request by wthomson**
Spelling correction.

### CODE REVIEW

**Comment by TrystanLea** [comment]
thanks @wthomson is there a missing s after emoncms about half way down?

**Comment by wthomson** [comment]
I used http://www.sussex.ac.uk/informatics/punctuation/apostrophe/possessives
as a reference, but likely interpreted in incorrectly. I'll leave that one rup to you.

**Comment by Paul-Reed** [comment]
> I'll leave that one rup to you.

== I'll leave that one up to you
"I've waited years to correct a spelling mistake by Bill!"

**Comment by wthomson** [comment]
Tempi sure Fugits when yer havin' eh, Paul? ;-)

**Comment by TrystanLea** [comment]
interesting, il merge :)

**Pull request merged**
