### PR TITLE
Enable envvars to be used

### PR DESCRIPTION
**Pull request by borpin**
Update code to enable Envvars to be specified in the settings.ini

Needs testing!!!!!!

Discussion in #1452 refers

### CODE REVIEW

**Comment by relnah** [comment]
Getting unexpected error.
`settings.php file error
Copy and modify default.settings.php to settings.php
For more information about configure settings.php file go to http://emoncms.org`

I do not use settings.php. I clone this branch then copy in settings.ini with env vars in it.

I did another test, cloning stable branch and use same settings.ini and in my container edit process_settings.php to include the env vars method and the call to it. I did _not_ add the other changes on line 32-35. That seemed to work. Don't know if stable differs from master much though.

**Comment by relnah** [comment]
Disregard my last comment, I deleted it.
Seems to work.
Using this settings.ini (chopped upp the password just to try two envvars with static characters mixed in)
`[sql]
server = {{MYSQL_HOST}}
username = {{MYSQL_USER}}
password = {{MYSQL_PASSWORD1}}1{{MYSQL_PASSWORD2}}

[redis]
enabled = {{REDIS}}

[mqtt]
enabled = false

[log]
level = {{LOG_LEVEL}}`

**Comment by borpin** [comment]
> Seems to work.

Great, thanks.

For formatting code blocks, use 3 backticks on a line before and 3 on a line after. The single backticks just work within a single line (no CR).

Cheers

**Comment by TrystanLea** [comment]
Thanks @borpin @relnah, finally tested here both using the emoncms-docker and a standard image, working well, merged in.

**Pull request merged**
